welcome = "Thanks for using potato file system."

[global]
is_debug = true
log_level = "DEBUG"
profile_path = "/Users/harry/pprof"

[volume]
ip = "127.0.0.1"
port = "8864"
peers = ["127.0.0.1:8864","127.0.0.1:7749","127.0.0.1:6636"]
is_master = true
db_data_dir = "/Volumes/HDD3/4/d"
db_value_dir = "/Volumes/HDD3/4/v"
db_syncwrites = false
meta_dir = "/Volumes/HDD3/4/meta"
max_size_mb = 32
cache_size_mb = 1024
# cache_max_entity_size_byte should be less than (cache_size_mb * 1024 *1024) /1024
cache_max_entity_size_byte = 524288

[http]
ip = "127.0.0.1"
port = "8874"
site_url = "http://dev-mac.bigfaceai.com"
#site_url = "http://127.0.0.1:8874"
static_dir = "./static"
temp_upload_dir = "/Volumes/HDD3/4/temp"
log_file = "/Volumes/HDD3/4/access.log"
favicon_file = "./templates/v1/favicon.ico"
cors_enabled = false
cors_allow_origins= ["http://127.0.0.1:8874"]
cors_allow_methods= ["PUT","GET","POST"]
cors_allow_headers= ["Origin", "Content-Length", "Content-Type"]
cors_expose_headers= ["Content-Length"]
cors_allow_credentials = true
cors_maxage_hours = 72