welcome = "Thanks for using potato file system."

[global]
log_level = "DEBUG"

[volume]
ip = "127.0.0.1"
port = "8864"
db_data_dir = "/Volumes/HDD2/4/d"
db_value_dir = "/Volumes/HDD2/4/v"

[http]
ip = "127.0.0.1"
port = "9981"
site_url = "//127.0.0.1:9981"
temp_dir = "/Volumes/HDD2/4/temp"
