welcome = "Thanks for using potato file system."

[global]
is_debug = true
log_level = "DEBUG"

[volume]
ip = "127.0.0.1"
port = "8864"
db_data_dir = "/Volumes/HDD2/4/d"
db_value_dir = "/Volumes/HDD2/4/v"
meta_dir = "/Volumes/HDD2/4/meta"
max_size = 33554432
max_cache_size = 33554432
cache_self = "http://127.0.0.1:8081"
cache_peers = ["http://127.0.0.1:8082","http://127.0.0.1:8083"]

[http]
ip = "127.0.0.1"
port = "8874"
site_url = "http://127.0.0.1:8874"
temp_dir = "/Volumes/HDD2/4/temp"

[replication]
is_master = true
slaves = ["127.0.0.1:7749","127.0.0.1:6636"]