welcome = "Welcome. Thanks for choosing PotatoFS."
version = "1.0.1"
debug = true

ip = "127.0.0.1"
volume_port = "4040"
http_port = "8080"
max_size_mb = 64

site_url = "http://127.0.0.1:8080"
upload_dir = "/Volumes/HDD4/data/potatofs/upload"

meta_dir = "/Volumes/HDD4/data/potatofs/meta"
data_dir = "/Volumes/HDD4/data/potatofs/data"

log_file = "/Volumes/HDD4/data/potatofs/logs/potatofs.log"
log_level = "debug"

is_master = true
sync_slave = "127.0.0.1:4050"
sync_pagesize = 100