welcome = "Thanks for using potato file system."

[global]
is_debug = true
log_level = "DEBUG"

[volume]
ip = "172.16.32.45"
port = "8864"
peers = ["172.16.32.45:8864","172.16.32.45:7749","172.16.32.45:6636"]
is_master = true
db_data_dir = "/home/ops/dev/data/pfs/d"
db_value_dir = "/home/ops/dev/data/pfs/v"
meta_dir = "/home/ops/dev/data/pfs/meta"
max_size_mb = 32
cache_size_mb = 1024

[http]
ip = "172.16.32.45"
port = "8874"
site_url = "http://172.16.32.45:8874"
static_dir = "/home/ops/dev/vendor/go3rd/src/potatofs/static"
temp_upload_dir = "/home/ops/dev/data/pfs/temp"
log_file = "/home/ops/dev/data/pfs/access.log"
favicon_file = "/home/ops/dev/vendor/go3rd/src/potatofs/static/v1/favicon.ico"
cors_enabled = false
cors_allow_origins= ["http://172.16.32.45:8874"]
cors_allow_methods= ["PUT","GET","POST"]
cors_allow_headers= ["Origin", "Content-Length", "Content-Type"]
cors_expose_headers= ["Content-Length"]
cors_allow_credentials = true
cors_maxage_hours = 72
