paths:
  /api/v1/addr/del:
    post:
      description: 用于删除指定的用户地址
      operationId: del
      parameters:
      - description: token
        in: body
        name: token
        required: true
        type: string
      - description: 地址id
        in: body
        name: id
        required: true
        type: string
      responses: {}
      summary: 删除用户地址
      tags:
      - addr
swagger: "2.0"
